### ISSUE TITLE
Gui Konzept umstellen

### ISSUE THREAD

**Issue by Tristan-H11** [Tristan-H11/Kryptographie#126]
Die gui wird von einer Startseite mit Client Ansichten auf ein neues Bedienkonzept umgestellt, um die Einbindung weiterer Verschlüsselungs und Signaturverfahren zu ermöglichen.

Auf der Startseite gibt es nun keine Konfiguration mehr und entsprechend Knöpfe "für Alice/Bob bestimmen", sondern Knöpfe, welche einen Konfigurationsdialog für den jeweiligen Client öffnen. In diesem Dialog können dann rsa (und ggf auch Elgamal) Schlüssel erstellt werden.

Es gibt keine Client Ansichten mit Interaktionsmöglichkeiten mehr. Es gibt eine Komponente, welche alle Informationen über einen Client darstellt. Dies ist eine reine Informationsseite und zeigt alle Komponenten von allen Konfigurieren Schlüssel(paaren) an.

Als Ersatz für die alten Client Ansichten, welche die Kommunikation ermöglicht haben, muss nun über einen Knopf im Menü ein Gespräch erstellt werden.
Beim Erstellen des Gespräch müssen die Beiden Partner, sowie den zu verwendenden Schlüssel des jeweiligen Partners gewählt werden. Anschließen erscheinen zwei neue Ansichten "Client A zu Client B" und "Client B zu Client A".
Wenn bspw ein Gespräch zwischen Alice und Bob erstellt und für Alice ein Elgamal Schlüssel und für Bob ein RSA Schlüssel gewählt werden, dann wird Bob seine Nachrichten an Alice mit Elgamal verschlüsseln, Alice ihre an Bob mit Rsa. Gleiches gilt für die Signaturen.

Die Mathefunktionen bekommen einen übergeordneten Menüpunkt, unter welchem eine Tab-Ansicht zu finden ist, welche dann die einzelnen Mathematischen Komponenten beinhaltet.

**Comment by ACTOPLM** [comment]
Kann man zwar so machen, aber wieso nicht wie folgt:

in der vorhandenen Maske der Schlüsselerzeugung wird ein Enum Feld hinzugefügt, in diesem kann ausgewählt werden, ob "RSA", "Elgamal", "WLD" , "was auch immer"

Wenn man ein Enum Feld umstellt, werden alle anderen auf das gleiche gestellt (geht recht easy wenn alle auf den gleichen Value in der Component verweisen)

Dann haben wir eine Funktionalität wie beim Power Knopf, mit welchem im backend api Service entschiedenen werden kann, welche Berechnungsmethode verwendet wird

Dann muss nicht so extrem viel umgebaut werden und es bleibt ein ziemlich sauberes Konzept (auch wenn das neue mit Sicherheit auch ein sauberes Konzept wäre)

**Comment by Tristan-H11** [comment]
Ansicht für symmetrische Verschlüsselung schaffen. Da gibts dann ein Dropdown, welche genutzt werden soll und abhängig davon werden einem dann mögliche Felder wie Key, IV und andere angezeigt.
Da gibts dann ein Feld "Eingabe" und eins "Ausgabe". Unten zwei Knöpfe "encrypt" und "decrypt". Es passiert also beides in der gleichen Ansicht.
